from enum import Enum


class Role(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    SECURITY_GUARD = "SECURITY_GUARD"
    EMPLOYEE = "EMPLOYEE"


class EmployeeStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class GateStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class CredentialStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    USED = "USED"
    COMPLETED = "COMPLETED"


class SubjectType(str, Enum):
    EMPLOYEE = "EMPLOYEE"
    VISITOR = "VISITOR"
    DELIVERY = "DELIVERY"


class VisitorStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    INSIDE = "INSIDE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class DeliveryStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    INSIDE = "INSIDE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class Purpose(str, Enum):
    MATERIAL_DELIVERY = "MATERIAL_DELIVERY"
    MATERIAL_PICKUP = "MATERIAL_PICKUP"
    BUSINESS_MEETING = "BUSINESS_MEETING"
    CLIENT_VISIT = "CLIENT_VISIT"
    VENDOR_VISIT = "VENDOR_VISIT"
    MAINTENANCE = "MAINTENANCE"
    INSTALLATION = "INSTALLATION"
    REPAIR = "REPAIR"
    INTERVIEW = "INTERVIEW"
    OTHER = "OTHER"


# Purposes that must carry at least one supporting document.
DOCUMENT_REQUIRED_PURPOSES = {Purpose.MATERIAL_DELIVERY, Purpose.MATERIAL_PICKUP}


class DocumentType(str, Enum):
    INVOICE = "INVOICE"
    DELIVERY_CHALLAN = "DELIVERY_CHALLAN"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    OTHER = "OTHER"


class Direction(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"


class AccessStatus(str, Enum):
    GRANTED = "GRANTED"
    DENIED = "DENIED"


class DenialReason(str, Enum):
    INVALID_QR = "INVALID_QR"
    EXPIRED_QR = "EXPIRED_QR"
    REVOKED_QR = "REVOKED_QR"
    WRONG_GATE = "WRONG_GATE"
    OUTSIDE_ALLOWED_TIME = "OUTSIDE_ALLOWED_TIME"
    UNAUTHORIZED_PERSON = "UNAUTHORIZED_PERSON"
    INACTIVE_EMPLOYEE = "INACTIVE_EMPLOYEE"
    EXPIRED_VISITOR_PASS = "EXPIRED_VISITOR_PASS"
    DELIVERY_CANCELLED = "DELIVERY_CANCELLED"
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    INVALID_DOCUMENT = "INVALID_DOCUMENT"
    NO_ACCESS_POLICY = "NO_ACCESS_POLICY"
    ALREADY_INSIDE = "ALREADY_INSIDE"
    NOT_INSIDE = "NOT_INSIDE"
    OTHER = "OTHER"
